# Capstone Project (Week 5)

### Import libraries

In [43]:
!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation
from bs4 import BeautifulSoup

from sklearn.cluster import KMeans # import k-means 

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Solving environment: done

# All requested packages already installed.

Solving environment: done

# All requested packages already installed.

Folium installed
Libraries imported.

### KL neighborhood with latitude and longitude

In [45]:
KL_NBhood = {'Neighborhood':['Kuala Lumpur City Centre','Ampang','TTDI','Bangsar','Seputeh','Damansara Heights',
'Desa Sri Hartamas','Desa ParkCity','Bukit Tunku','Mont Kiara','Mutiara Damansara', 'Subang Jaya','Cyberjaya',
'Seri Kembangan', 'Kajang', 'Shah Alam', 'Klang', 'Sungai Buloh', 'Bangi', 'Semenyih', 'Batu Caves'],
'Latitude':[3.1516636,3.1521349,3.1508079,3.13083,3.1136874,3.151148,3.1631076,3.1866282,3.1646734,3.1651961,3.1585644,
           3.0567521, 2.9252375, 3.0340649, 2.9932788, 3.05650145, 3.0471533, 3.21, 2.9040335, 2.9473911, 3.2380198],
'Longitude':[101.6943028,101.7322499,101.6249189,101.66944,101.68142,101.657635,101.6496903,101.6303087,101.6815526,101.6489408,
            101.6037424, 101.5854671, 101.6484853, 101.7055684, 101.7877551, 101.525085119032, 101.4492077, 101.55, 
            101.786142761094, 101.8459911, 101.6829764]}

df = pd.DataFrame.from_dict(KL_NBhood)

In [46]:
df

                Neighborhood  Latitude   Longitude
0   Kuala Lumpur City Centre  3.151664  101.694303
1                     Ampang  3.152135  101.732250
2                       TTDI  3.150808  101.624919
3                    Bangsar  3.130830  101.669440
4                    Seputeh  3.113687  101.681420
5          Damansara Heights  3.151148  101.657635
6          Desa Sri Hartamas  3.163108  101.649690
7              Desa ParkCity  3.186628  101.630309
8                Bukit Tunku  3.164673  101.681553
9                 Mont Kiara  3.165196  101.648941
10         Mutiara Damansara  3.158564  101.603742
11               Subang Jaya  3.056752  101.585467
12                 Cyberjaya  2.925238  101.648485
13            Seri Kembangan  3.034065  101.705568
14                    Kajang  2.993279  101.787755
15                 Shah Alam  3.056501  101.525085
16                     Klang  3.047153  101.449208
17              Sungai Buloh  3.210000  101.550000
18                     Bangi  2.904034  101.786143
19                  Semenyih  2.947391  101.845991
20                Batu Caves  3.238020  101.682976

### Foursquare Credential

In [47]:
CLIENT_ID = '52DWPOWI3BQ0XTTKT1SP2B1JIBCNIH0JPGNSM2Z05WRQI35X' 
CLIENT_SECRET = 'SET1OO5SCNJYL2WEAPVG2QZOXLZ5MMHTORMRF4H1TE1KULUR' 
VERSION = '20180604'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 52DWPOWI3BQ0XTTKT1SP2B1JIBCNIH0JPGNSM2Z05WRQI35X
CLIENT_SECRET:SET1OO5SCNJYL2WEAPVG2QZOXLZ5MMHTORMRF4H1TE1KULUR

In [48]:
address = 'Kuala Lumpur, MY'

geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  This is separate from the ipykernel package so we can avoid doing imports until

3.1516636 101.6943028

### Plot KL neighborhood on map

In [49]:
# create map of Kuala Lumpur using latitude and longitude values
map_KL = folium.Map(location=[latitude, longitude], zoom_start=10)

# add markers to map
for lat, lng, neighborhood in zip(df['Latitude'], df['Longitude'], df['Neighborhood']):
    label = '{}'.format(neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_KL)  
    
map_KL

### Explore Neighborhood in KL

In [50]:
ShoppingMallID='4bf58dd8d48988d1fd941735'
ShoppingPlazaID='5744ccdfe4b0c0459246b4dc'
BurgerJointID='4bf58dd8d48988d16c941735'
SchoolID='4bf58dd8d48988d13b941735'
OfficeID='4bf58dd8d48988d124941735'
CollegeUniID='4d4b7105d754a06372d81259'

radius=5000
categoryID='4bf58dd8d48988d16c941735'
search_query='burger'
search_query2='school'
search_query3='office'

### Check out the burger restaurants in KL neighborhood

In [51]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    latitude, 
    longitude, 
    VERSION, 
    search_query, 
    radius, 
    LIMIT)

results = requests.get(url).json()

df_burger = json_normalize(results['response']['venues'])

df_burger.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.neighborhood,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",False,4c70d253df6b8cfa2397b94d,"11 & 13, Jalan Tun Perak",MY,Kuala Lumpur,Malaysia,NaN,398,"[11 & 13, Jalan Tun Perak, 50150 Kuala Lumpur,...","[{'label': 'display', 'lat': 3.149030019048331...",3.149030,101.696731,NaN,50150,Kuala Lumpur,Burger King,v-1548042210,NaN
1,"[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",False,4b1f23c7f964a520582424e3,KL Sentral,MY,Kuala Lumpur,Malaysia,"DH3A Level 1, Departure Transit",2152,"[KL Sentral (DH3A Level 1, Departure Transit),...","[{'label': 'display', 'lat': 3.134109875829454...",3.134110,101.686192,NaN,50470,Kuala Lumpur,Burger King,v-1548042210,NaN
2,"[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",False,59b54e9ffdb9a771a6dc39d8,residensi utmkl,MY,Kuala Lumpur,Malaysia,jalan maktab,3784,"[residensi utmkl (jalan maktab), 54000 Kuala L...","[{'label': 'display', 'lat': 3.171621083667579...",3.171621,101.721867,NaN,54000,Kuala Lumpur,Burger King,v-1548042210,NaN
3,"[{'id': '4bf58dd8d48988d16c941735', 'name': 'B...",False,4e92988d55037de99d705861,Lorong Bunus 3,MY,Kuala Lumpur,Malaysia,NaN,477,"[Lorong Bunus 3, Kuala Lumpur, Federal Territo...","[{'label': 'display', 'lat': 3.153216748366833...",3.153217,101.698309,NaN,NaN,Federal Territory of Kuala Lum,Berlida Ramlee Burger,v-1548042210,NaN
4,"[{'id': '4bf58dd8d48988d16c941735', 'name': 'B...",False,571c5873498ea23e6c52b0e2,Sunway Putra Mall,MY,NaN,Malaysia,NaN,1652,"[Sunway Putra Mall, Malaysia]","[{'label': 'display', 'lat': 3.166384563292114...",3.166385,101.692387,NaN,NaN,NaN,Friends of Burger,v-1548042210,NaN

### Check out the schools in KL neighborhood

In [52]:
url2 = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    latitude, 
    longitude, 
    VERSION, 
    search_query2, 
    radius, 
    LIMIT)

results2 = requests.get(url2).json()

df_school = json_normalize(results2['response']['venues'])

df_school.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.neighborhood,location.postalCode,location.state,name,referralId
0,"[{'id': '4bf58dd8d48988d198941735', 'name': 'C...",False,4fcdc6dae4b023dee7e07934,Bangunan Yayasan Selangor,MY,Kampung Baru,Malaysia,NaN,2472,"[Bangunan Yayasan Selangor, 50250 Kampung Baru...","[{'label': 'display', 'lat': 3.168328433495078...",3.168328,101.709012,NaN,50250,Kuala Lumpur,Universiti Kuala Lumpur Business School (UBIS),v-1548042217
1,"[{'id': '4bf58dd8d48988d13d941735', 'name': 'H...",False,4ba30704f964a520882838e3,Jalan Syed Putra,MY,Kuala Lumpur,Malaysia,NaN,2298,"[Jalan Syed Putra, 55150 Kuala Lumpur, Kuala L...","[{'label': 'display', 'lat': 3.131179549529693...",3.131180,101.691738,NaN,55150,Kuala Lumpur,Kuen Cheng High School (坤成中学),v-1548042217
2,"[{'id': '52e81612bcbc57f1066b7a46', 'name': 'P...",False,4cf1dad0e3b9a0932d704153,Lorong Hang Jebat,MY,Kuala Lumpur,Malaysia,NaN,1018,"[Lorong Hang Jebat, 50150 Kuala Lumpur, Kuala ...","[{'label': 'display', 'lat': 3.144029859758255...",3.144030,101.699360,NaN,50150,Kuala Lumpur,Confucian Private Secondary School,v-1548042217
3,"[{'id': '4bf58dd8d48988d13d941735', 'name': 'H...",False,4ceb8217f3bda143ec2fcce4,Jalan Cenderasari,MY,Kuala Lumpur,Malaysia,NaN,953,"[Jalan Cenderasari, 50480 Kuala Lumpur, Kuala ...","[{'label': 'display', 'lat': 3.143579220670883...",3.143579,101.691472,NaN,50480,Kuala Lumpur,Methodist Girls School,v-1548042217
4,"[{'id': '4bf58dd8d48988d198941735', 'name': 'C...",False,4d2a60798292236a44462bbb,Jalan Munsyi Abdullah,MY,Kuala Lumpur,Malaysia,NaN,225,"[Jalan Munsyi Abdullah, 50100 Kuala Lumpur, Ku...","[{'label': 'display', 'lat': 3.150496794338682...",3.150497,101.692639,NaN,50100,Kuala Lumpur,"Razak School of Government, UNIRAZAK",v-1548042217

### Check out the offices in KL neighborhood

In [53]:
url3 = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    latitude, 
    longitude, 
    VERSION, 
    search_query3, 
    radius, 
    LIMIT)

results3 = requests.get(url3).json()

df_office = json_normalize(results3['response']['venues'])

df_office.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.neighborhood,location.postalCode,location.state,name,referralId
0,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",False,56010fe3498efeb05826ead8,Menara 1 Sentrum,MY,Kuala Lumpur,Malaysia,"No 201, Jalan Tun Sambanthan",2123,"[Menara 1 Sentrum (No 201, Jalan Tun Sambantha...","[{'label': 'display', 'lat': 3.133666678143967...",3.133667,101.687960,Kuala Lumpur Sentral,50470,Kuala Lumpur,Google Vendor Office (GOVO),v-1548042223
1,"[{'id': '4bf58dd8d48988d130941735', 'name': 'B...",False,4e150a6c18a8addae8c6aed9,24 Floor,MY,Wilayah Persekutuan,Malaysia,NaN,264,"[24 Floor, 50530 Wilayah Persekutuan, Kuala Lu...","[{'label': 'display', 'lat': 3.154010625299993...",3.154011,101.694660,NaN,50530,Kuala Lumpur,Kwsp Equity Research (Office Wan Cool Art),v-1548042223
2,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",False,4ec5ca160e6158bafc957cfd,"No.8, Lorong Ceylon,",MY,Kuala Lumpur,Malaysia,Lorong Ceylon Off Jalan Raja Chulan,1514,"[No.8, Lorong Ceylon, (Lorong Ceylon Off Jalan...","[{'label': 'display', 'lat': 3.148694674278082...",3.148695,101.707596,NaN,50250,Kuala Lumpur,Seri Bukit Ceylon Office & Residences,v-1548042223
3,"[{'id': '4f04b1572fb6e1c99f3db0bf', 'name': 'S...",False,4f6afd4de4b07984c1328da0,Bank Negara Malaysia,MY,Kuala Lumpur,Malaysia,NaN,408,"[Bank Negara Malaysia, 50929 Kuala Lumpur, Kua...","[{'label': 'display', 'lat': 3.154497973966482...",3.154498,101.691972,NaN,50929,Kuala Lumpur,Maintenance Office,v-1548042223
4,"[{'id': '4bf58dd8d48988d130941735', 'name': 'B...",False,4d928431a79d530c7c64ff72,No. 1 Jalan Nagasari (Off Jalan Raja Chulan),MY,Kuala Lumpur,Malaysia,NaN,1604,"[No. 1 Jalan Nagasari (Off Jalan Raja Chulan),...","[{'label': 'display', 'lat': 3.148792537798102...",3.148793,101.708446,NaN,502000,Kuala Lumpur,The Lion Group - One Residency (Office Tower),v-1548042223

In [54]:
# keep relevant columns 
filtered_col = ['id', 'name', 'categories', 'location.city', 'location.distance', 'location.lat', 'location.lng']
df_burger_filtered = df_burger.loc[:, filtered_col]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
df_burger_filtered['categories'] = df_burger_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
df_burger_filtered.columns = [col.split('.')[-1] for col in df_burger_filtered.columns]

df_burger_filtered.head()

,id,name,categories,city,distance,lat,lng
0,4c70d253df6b8cfa2397b94d,Burger King,Fast Food Restaurant,Kuala Lumpur,398,3.149030,101.696731
1,4b1f23c7f964a520582424e3,Burger King,Fast Food Restaurant,Kuala Lumpur,2152,3.134110,101.686192
2,59b54e9ffdb9a771a6dc39d8,Burger King,Fast Food Restaurant,Kuala Lumpur,3784,3.171621,101.721867
3,4e92988d55037de99d705861,Berlida Ramlee Burger,Burger Joint,Kuala Lumpur,477,3.153217,101.698309
4,571c5873498ea23e6c52b0e2,Friends of Burger,Burger Joint,NaN,1652,3.166385,101.692387

In [55]:
# keep relevant columns 
df_school_filtered = df_school.loc[:, filtered_col]

# filter the category for each row
df_school_filtered['categories'] = df_school_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
df_school_filtered.columns = [col.split('.')[-1] for col in df_school_filtered.columns]

df_school_filtered.head()

,id,name,categories,city,distance,lat,lng
0,4fcdc6dae4b023dee7e07934,Universiti Kuala Lumpur Business School (UBIS),College Academic Building,Kampung Baru,2472,3.168328,101.709012
1,4ba30704f964a520882838e3,Kuen Cheng High School (坤成中学),High School,Kuala Lumpur,2298,3.131180,101.691738
2,4cf1dad0e3b9a0932d704153,Confucian Private Secondary School,Private School,Kuala Lumpur,1018,3.144030,101.699360
3,4ceb8217f3bda143ec2fcce4,Methodist Girls School,High School,Kuala Lumpur,953,3.143579,101.691472
4,4d2a60798292236a44462bbb,"Razak School of Government, UNIRAZAK",College Academic Building,Kuala Lumpur,225,3.150497,101.692639

In [56]:
# keep relevant columns 
df_office_filtered = df_office.loc[:, filtered_col]

# filter the category for each row
df_office_filtered['categories'] = df_office_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
df_office_filtered.columns = [col.split('.')[-1] for col in df_office_filtered.columns]

df_office_filtered.head()

,id,name,categories,city,distance,lat,lng
0,56010fe3498efeb05826ead8,Google Vendor Office (GOVO),Office,Kuala Lumpur,2123,3.133667,101.687960
1,4e150a6c18a8addae8c6aed9,Kwsp Equity Research (Office Wan Cool Art),Building,Wilayah Persekutuan,264,3.154011,101.694660
2,4ec5ca160e6158bafc957cfd,Seri Bukit Ceylon Office & Residences,Office,Kuala Lumpur,1514,3.148695,101.707596
3,4f6afd4de4b07984c1328da0,Maintenance Office,Storage Facility,Kuala Lumpur,408,3.154498,101.691972
4,4d928431a79d530c7c64ff72,The Lion Group - One Residency (Office Tower),Building,Kuala Lumpur,1604,3.148793,101.708446

### Function from class: search nearby venues within some defined maters from the latitude and longitude

In [57]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [58]:
KL_venues = getNearbyVenues(names=df['Neighborhood'],
                                   latitudes=df['Latitude'],
                                   longitudes=df['Longitude']
                                  )

Kuala Lumpur City Centre
Ampang
TTDI
Bangsar
Seputeh
Damansara Heights
Desa Sri Hartamas
Desa ParkCity
Bukit Tunku
Mont Kiara
Mutiara Damansara
Subang Jaya
Cyberjaya
Seri Kembangan
Kajang
Shah Alam
Klang
Sungai Buloh
Bangi
Semenyih
Batu Caves

### Check the dataframe size

In [59]:
print(KL_venues.shape)
KL_venues.head()

(438, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Kuala Lumpur City Centre,3.151664,101.694303,Dataran Merdeka Kuala Lumpur,3.149900,101.693840,Athletics & Sports
1,Kuala Lumpur City Centre,3.151664,101.694303,Kebab Jln TAR,3.153206,101.695941,Middle Eastern Restaurant
2,Kuala Lumpur City Centre,3.151664,101.694303,Syawarma Raihani Kebab,3.153069,101.696364,Moroccan Restaurant
3,Kuala Lumpur City Centre,3.151664,101.694303,Restoran Jai Hind,3.151061,101.696074,Indian Restaurant
4,Kuala Lumpur City Centre,3.151664,101.694303,Cafeteria DBKL,3.152154,101.694922,Asian Restaurant

### Summarize venue by neighborhood

In [60]:
KL_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
Ampang,4,4,4,4,4,4
Bangi,12,12,12,12,12,12
Bangsar,30,30,30,30,30,30
Batu Caves,9,9,9,9,9,9
Bukit Tunku,2,2,2,2,2,2
Cyberjaya,30,30,30,30,30,30
Damansara Heights,30,30,30,30,30,30
Desa ParkCity,21,21,21,21,21,21
Desa Sri Hartamas,30,30,30,30,30,30
Kajang,30,30,30,30,30,30
Klang,30,30,30,30,30,30
Kuala Lumpur City Centre,30,30,30,30,30,30
Mont Kiara,30,30,30,30,30,30
Mutiara Damansara,29,29,29,29,29,29
Semenyih,30,30,30,30,30,30
Seputeh,18,18,18,18,18,18
Seri Kembangan,26,26,26,26,26,26
Shah Alam,12,12,12,12,12,12
Subang Jaya,4,4,4,4,4,4
Sungai Buloh,1,1,1,1,1,1
TTDI,30,30,30,30,30,30

### Determine the # of unique catoegories

In [61]:
print('There are {} uniques categories.'.format(len(KL_venues['Venue Category'].unique())))

There are 130 uniques categories.

### Analyze each neighborhood in KL

In [62]:
# one hot encoding
KL_onehot = pd.get_dummies(KL_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
KL_onehot['Neighborhood'] = KL_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [KL_onehot.columns[-1]] + list(KL_onehot.columns[:-1])
KL_onehot = KL_onehot[fixed_columns]

KL_onehot.head()

,Neighborhood,African Restaurant,Arcade,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,BBQ Joint,Bakery,Bar,...,Surf Spot,Sushi Restaurant,Tattoo Parlor,Thai Restaurant,Theater,Train Station,Udon Restaurant,Vegetarian / Vegan Restaurant,Vineyard,Yoga Studio
0,Kuala Lumpur City Centre,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Kuala Lumpur City Centre,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Kuala Lumpur City Centre,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Kuala Lumpur City Centre,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Kuala Lumpur City Centre,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [63]:
KL_onehot.shape

(438, 131)

In [64]:
KL_grouped = KL_onehot.groupby('Neighborhood').mean().reset_index()
KL_grouped

,Neighborhood,African Restaurant,Arcade,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,BBQ Joint,Bakery,Bar,...,Surf Spot,Sushi Restaurant,Tattoo Parlor,Thai Restaurant,Theater,Train Station,Udon Restaurant,Vegetarian / Vegan Restaurant,Vineyard,Yoga Studio
0,Ampang,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Bangi,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Bangsar,0.000000,0.000000,0.000000,0.066667,0.000000,0.000000,0.000000,0.000000,0.033333,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Batu Caves,0.000000,0.000000,0.000000,0.000000,0.111111,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Bukit Tunku,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,Cyberjaya,0.000000,0.000000,0.000000,0.000000,0.066667,0.000000,0.033333,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Damansara Heights,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Desa ParkCity,0.047619,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.047619,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,Desa Sri Hartamas,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.033333,0.033333,...,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333
9,Kajang,0.000000,0.033333,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,Klang,0.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,Kuala Lumpur City Centre,0.000000,0.000000,0.033333,0.000000,0.033333,0.066667,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.033333,0.000000,0.000000
12,Mont Kiara,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.033333,0.033333,...,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333
13,Mutiara Damansara,0.000000,0.000000,0.000000,0.000000,0.103448,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,Semenyih,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.033333,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,Seputeh,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.055556,0.000000,0.055556,0.055556,0.055556,0.000000,0.000000
16,Seri Kembangan,0.000000,0.000000,0.000000,0.000000,0.076923,0.000000,0.000000,0.000000,0.000000,...,0.038462,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.038462,0.000000,0.000000
17,Shah Alam,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.083333,0.000000
18,Subang Jaya,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,Sungai Buloh,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,TTDI,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.033333,0.033333,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [65]:
KL_grouped.shape

(21, 131)

In [66]:
num_top_venues = 5

for NBH in KL_grouped['Neighborhood']:
    print("----"+NBH+"----")
    temp = KL_grouped[KL_grouped['Neighborhood'] == NBH].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Ampang----
                     venue  freq
0              Pizza Place  0.25
1             Intersection  0.25
2              Flower Shop  0.25
3              Golf Course  0.25
4  North Indian Restaurant  0.00


----Bangi----
                   venue  freq
0             Restaurant  0.08
1           Burger Joint  0.08
2  Indonesian Restaurant  0.08
3      Indian Restaurant  0.08
4         Ice Cream Shop  0.08


----Bangsar----
               venue  freq
0  Indian Restaurant  0.10
1     Cosmetics Shop  0.07
2         Steakhouse  0.07
3      Shopping Mall  0.07
4     Ice Cream Shop  0.07


----Batu Caves----
               venue  freq
0  Convenience Store  0.22
1   Malay Restaurant  0.22
2  Indian Restaurant  0.11
3   Asian Restaurant  0.11
4          Gift Shop  0.11


----Bukit Tunku----
                       venue  freq
0                      Hotel   0.5
1             Scenic Lookout   0.5
2  Middle Eastern Restaurant   0.0
3                   Pharmacy   0.0
4                  Pet Store   0.0


----Cyberjaya----
                       venue  freq
0         Chinese Restaurant  0.10
1  Middle Eastern Restaurant  0.07
2           Asian Restaurant  0.07
3      Indonesian Restaurant  0.07
4               Noodle House  0.07


----Damansara Heights----
                 venue  freq
0                 Café  0.17
1    Convenience Store  0.10
2     Malay Restaurant  0.10
3                  Gym  0.07
4  Japanese Restaurant  0.07


----Desa ParkCity----
                venue  freq
0                Café  0.14
1         Coffee Shop  0.10
2  African Restaurant  0.05
3      Ice Cream Shop  0.05
4                 Gym  0.05


----Desa Sri Hartamas----
                 venue  freq
0  Japanese Restaurant  0.17
1                 Café  0.17
2    Korean Restaurant  0.10
3           Restaurant  0.07
4          Yoga Studio  0.03


----Kajang----
               venue  freq
0   Malay Restaurant  0.17
1  Convenience Store  0.10
2  Mobile Phone Shop  0.07
3        Gas Station  0.03
4           Pharmacy  0.03


----Klang----
                venue  freq
0  Chinese Restaurant  0.30
1    Asian Restaurant  0.17
2    Malay Restaurant  0.13
3   Indian Restaurant  0.07
4       Shopping Mall  0.07


----Kuala Lumpur City Centre----
                  venue  freq
0     Indian Restaurant  0.20
1                  Café  0.07
2    Athletics & Sports  0.07
3  Chettinad Restaurant  0.03
4            Food Court  0.03


----Mont Kiara----
                 venue  freq
0  Japanese Restaurant  0.17
1    Korean Restaurant  0.13
2                 Café  0.10
3           Restaurant  0.07
4           Hotel Pool  0.03


----Mutiara Damansara----
                 venue  freq
0     Malay Restaurant  0.21
1     Asian Restaurant  0.10
2           Restaurant  0.10
3                 Café  0.07
4  Sporting Goods Shop  0.07


----Semenyih----
                venue  freq
0    Malay Restaurant  0.23
1  Chinese Restaurant  0.20
2                Café  0.07
3        Noodle House  0.07
4          Restaurant  0.03


----Seputeh----
               venue  freq
0        Coffee Shop  0.11
1  Martial Arts Dojo  0.06
2         Campground  0.06
3          Rest Area  0.06
4         Food Court  0.06


----Seri Kembangan----
                       venue  freq
0         Chinese Restaurant  0.23
1                 Restaurant  0.12
2  Middle Eastern Restaurant  0.08
3           Asian Restaurant  0.08
4                Coffee Shop  0.08


----Shah Alam----
              venue  freq
0  Malay Restaurant  0.17
1              Food  0.08
2          Vineyard  0.08
3              Park  0.08
4     Train Station  0.08


----Subang Jaya----
                venue  freq
0         Pizza Place  0.25
1      Cosmetics Shop  0.25
2   Electronics Store  0.25
3    Basketball Court  0.25
4  African Restaurant  0.00


----Sungai Buloh----
                                      venue  freq
0  Residential Building (Apartment / Condo)   1.0
1                        African Restaurant   0.0
2                 Middle Eastern Restaurant   0.0
3                                  Pharmacy   0.0
4                                 Pet Store   0.0


----TTDI----
                venue  freq
0          Restaurant  0.10
1         Coffee Shop  0.10
2  Chinese Restaurant  0.07
3           Bookstore  0.07
4                Café  0.07

### Function from class that sort venues in descending order

In [67]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [68]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = KL_grouped['Neighborhood']

for ind in np.arange(KL_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(KL_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Ampang,Pizza Place,Intersection,Golf Course,Flower Shop,Department Store,Doctor's Office,Dog Run,Dance Studio,Donut Shop,Food
1,Bangi,Creperie,Breakfast Spot,Food Court,Market,Ice Cream Shop,Indian Restaurant,Indonesian Restaurant,Department Store,Convenience Store,Burger Joint
2,Bangsar,Indian Restaurant,Shopping Mall,Ice Cream Shop,Coffee Shop,Clothing Store,Steakhouse,Cosmetics Shop,Arts & Crafts Store,Record Shop,Spa
3,Batu Caves,Malay Restaurant,Convenience Store,Cave,Halal Restaurant,Indian Restaurant,Asian Restaurant,Gift Shop,Event Space,Flower Shop,Flea Market
4,Bukit Tunku,Hotel,Scenic Lookout,Food,Dance Studio,Department Store,Doctor's Office,Dog Run,Donut Shop,Eastern European Restaurant,Electronics Store
5,Cyberjaya,Chinese Restaurant,Noodle House,Asian Restaurant,Middle Eastern Restaurant,Coffee Shop,Ice Cream Shop,Indonesian Restaurant,Japanese Restaurant,Pakistani Restaurant,Multiplex
6,Damansara Heights,Café,Convenience Store,Malay Restaurant,Japanese Restaurant,Gym,Club House,Pub,Food Court,College Quad,English Restaurant
7,Desa ParkCity,Café,Coffee Shop,African Restaurant,Spanish Restaurant,Ice Cream Shop,Japanese Restaurant,Juice Bar,Frozen Yogurt Shop,Fast Food Restaurant,Dog Run
8,Desa Sri Hartamas,Japanese Restaurant,Café,Korean Restaurant,Restaurant,Indonesian Restaurant,Dance Studio,Martial Arts Dojo,Kushikatsu Restaurant,Burger Joint,Italian Restaurant
9,Kajang,Malay Restaurant,Convenience Store,Mobile Phone Shop,Food Court,Multiplex,Moroccan Restaurant,Pharmacy,Pizza Place,Electronics Store,Chinese Restaurant
10,Klang,Chinese Restaurant,Asian Restaurant,Malay Restaurant,Indian Restaurant,Shopping Mall,Breakfast Spot,Coffee Shop,Fast Food Restaurant,Restaurant,Food
11,Kuala Lumpur City Centre,Indian Restaurant,Athletics & Sports,Café,Hotel,Boutique,Food Court,Flea Market,Men's Store,Middle Eastern Restaurant,Monument / Landmark
12,Mont Kiara,Japanese Restaurant,Korean Restaurant,Café,Restaurant,Yoga Studio,Ice Cream Shop,Kushikatsu Restaurant,Italian Restaurant,Indonesian Restaurant,Fruit & Vegetable Store
13,Mutiara Damansara,Malay Restaurant,Restaurant,Asian Restaurant,Café,Sporting Goods Shop,Farmers Market,Clothing Store,South Indian Restaurant,Food Court,Coffee Shop
14,Semenyih,Malay Restaurant,Chinese Restaurant,Café,Noodle House,Bookstore,Multiplex,Farmers Market,Fast Food Restaurant,Restaurant,Clothing Store
15,Seputeh,Coffee Shop,Hotel,Gym,Martial Arts Dojo,Chinese Restaurant,Food Court,Spa,Japanese Restaurant,Playground,Campground
16,Seri Kembangan,Chinese Restaurant,Restaurant,Asian Restaurant,Middle Eastern Restaurant,Coffee Shop,Gym,Pizza Place,Café,Bubble Tea Shop,Food Truck
17,Shah Alam,Malay Restaurant,Burger Joint,Frozen Yogurt Shop,Bus Stop,Park,Food Truck,Food,Cosmetics Shop,Gym,Train Station
18,Subang Jaya,Pizza Place,Electronics Store,Cosmetics Shop,Basketball Court,Flea Market,Fast Food Restaurant,Farmers Market,Event Space,English Restaurant,Eastern European Restaurant
19,Sungai Buloh,Residential Building (Apartment / Condo),Yoga Studio,Food,Dance Studio,Department Store,Doctor's Office,Dog Run,Donut Shop,Eastern European Restaurant,Electronics Store
20,TTDI,Coffee Shop,Restaurant,Café,Chinese Restaurant,Bookstore,Spa,Doctor's Office,Department Store,Event Space,Comedy Club

### Cluster Neighborhood

In [72]:
# set number of clusters
kclusters = 5

KL_grouped_clustering = KL_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(KL_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 0, 0, 4, 2, 0, 4, 0, 0, 4], dtype=int32)

In [73]:
KL_merged = df

# add clustering labels
KL_merged['Cluster Labels'] = kmeans.labels_

# merge KL_grouped with KL_data to add latitude/longitude for each neighborhood
KL_merged = KL_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

KL_merged.head()

,Neighborhood,Latitude,Longitude,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Kuala Lumpur City Centre,3.151664,101.694303,0,Indian Restaurant,Athletics & Sports,Café,Hotel,Boutique,Food Court,Flea Market,Men's Store,Middle Eastern Restaurant,Monument / Landmark
1,Ampang,3.152135,101.732250,0,Pizza Place,Intersection,Golf Course,Flower Shop,Department Store,Doctor's Office,Dog Run,Dance Studio,Donut Shop,Food
2,TTDI,3.150808,101.624919,0,Coffee Shop,Restaurant,Café,Chinese Restaurant,Bookstore,Spa,Doctor's Office,Department Store,Event Space,Comedy Club
3,Bangsar,3.130830,101.669440,4,Indian Restaurant,Shopping Mall,Ice Cream Shop,Coffee Shop,Clothing Store,Steakhouse,Cosmetics Shop,Arts & Crafts Store,Record Shop,Spa
4,Seputeh,3.113687,101.681420,2,Coffee Shop,Hotel,Gym,Martial Arts Dojo,Chinese Restaurant,Food Court,Spa,Japanese Restaurant,Playground,Campground

In [74]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(KL_merged['Latitude'], KL_merged['Longitude'], KL_merged['Neighborhood'], KL_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

### Check out the number of clusters

In [76]:
print('There are {} uniques categories.'.format(len(KL_merged['Cluster Labels'].unique())))

There are 5 uniques categories.

### 1st cluster

In [89]:
KL_merged[KL_merged['Cluster Labels'] == 0]['Neighborhood']

0     Kuala Lumpur City Centre
1                       Ampang
2                         TTDI
5            Damansara Heights
7                Desa ParkCity
8                  Bukit Tunku
11                 Subang Jaya
12                   Cyberjaya
15                   Shah Alam
16                       Klang
20                  Batu Caves
Name: Neighborhood, dtype: object

### 2nd cluster

In [90]:
KL_merged[KL_merged['Cluster Labels'] == 1]['Neighborhood']

19    Semenyih
Name: Neighborhood, dtype: object

### 3rd cluster

In [91]:
KL_merged[KL_merged['Cluster Labels'] == 2]['Neighborhood']

4    Seputeh
Name: Neighborhood, dtype: object

### 4th cluster

In [92]:
KL_merged[KL_merged['Cluster Labels'] == 3]['Neighborhood']

18    Bangi
Name: Neighborhood, dtype: object

### 5th cluster

In [93]:
KL_merged[KL_merged['Cluster Labels'] == 4]['Neighborhood']

3               Bangsar
6     Desa Sri Hartamas
9            Mont Kiara
10    Mutiara Damansara
13       Seri Kembangan
14               Kajang
17         Sungai Buloh
Name: Neighborhood, dtype: object

#### Conclusion: ABC burger can open their outlet in one/some of the city in cluster 1 as they are similar to Kuala Lumpur City Centre